#!/bin/bash

set -e

e="echo -e \t"

product_name_ver="Futurewei Data Orchestrator v0.1"
rootfs=/futurewei-data

$e "${product_name_ver}\n"

# Validate inputs and print usage

[ $# -lt 1 ] && $e "Usage:\t$0 <orchestration path> [namespace] [debug: 0 | 1]" && $e &&
    $e "\tPath needs to be a mounted path to a file or directory inside the Data Orchestration under $rootfs" && exit 1

# Setup input parameters

orchestration_path=$1
[ $2 ] && namespace=$2 && $e "Namespace = $namespace" && $e || namespace="default"
[ $3 ] && debug=$3 && $e "Debug = $debug" && $e || debug=
#($(kubectl get pods -n ${namespace} | grep "alluxio-master" | awk '{print $1}')) # or | sed 1d or awk 'NR>0'
orch_masters_pods="alluxio-master-0"

# Print important info
[ "$debug" != "0" ] && $e "Data Orchestration Master Pods : ${orch_masters_pods[*]}"

# Validate the specified node is an Orchestration worker node

$e "Listing the data:"
[ "$debug" != "0" ] && $e "\\kubectl exec -n ${namespace} -i ${orch_masters_pods[0]} -c alluxio-master -- alluxio fs ls --recursive ${orchestration_path}"

\kubectl exec -n ${namespace} -i ${orch_masters_pods[0]} -c alluxio-master -- alluxio fs ls --recursive ${orchestration_path}

echo -n -e "\t Are you sure to delete it? [Y/n]: "
read prompt

[ "$prompt" != "Y" ] && [ "$prompt" != "y" ] && $e "No data is deleted." && exit 1 || $e

$e "Deleting the data from ${product_name_ver} only. The under storage of this data at original location will not be affected."

[ "$debug" != "0" ] && $e "\kubectl exec -n ${namespace} -i ${orch_masters_pods[0]} -c alluxio-master -- alluxio fs rm -r --alluxioOnly ${orchestration_path}"

\kubectl exec -n ${namespace} -i ${orch_masters_pods[0]} -c alluxio-master -- alluxio fs rm -r --alluxioOnly ${orchestration_path}

exitcode=$?
[ "$debug" != "0" ] && $e "Return code: $exitcode"
return $exitcode
